export const data = [
  {
    key: '1',
    name: 'Book Now Link',
    color: '#B6CDFF',
    createdDate: 'Tuesday, 5 Feb 2019',
    is_active: true,
    isLocked: true,
    index: 0,
  },
  {
    key: '2',
    name: 'From a friend',
    color: '#9CF075',
    createdDate: 'Monday, 4 Feb 2019',
    is_active: false,
    isLocked: false,
    index: 1,
  },
  {
    key: '3',
    name: 'Instagram',
    color: '#F49598',
    createdDate: 'Tuesday, 5 Feb 2019',
    is_active: true,
    isLocked: true,
    index: 2,
  },
  {
    key: '4',
    name: 'Imported',
    color: '#4899DF',
    createdDate: 'Tuesday, 5 Feb 2019',
    is_active: true,
    isLocked: false,
    index: 3,
  },
  {
    key: '5',
    name: 'Walk-in',
    createdDate: 'Saturday, 14 April 2018',
    is_active: true,
    isLocked: false,
    index: 4,
  },
  {
    key: '6',
    name: 'Facebook',
    color: 'blue',
    createdDate: 'Saturday, 14 April 2018',
    is_active: true,
    isLocked: false,
    index: 5,
  },
  {
    key: '7',
    name: 'Fresha',
    createdDate: 'Tuesday, 5 Feb 2019',
    is_active: true,
    isLocked: false,
    index: 6,
  },
]
