export const title = 'Reports'
export const subtitle =
  'Setup which sections are accessible to each user permission level. All logged in staff can access the calendar, and owner accounts have full system access.'

export const columns = [
  {
    key: 'scheduler',
    title: 'Scheduler',
  },
  {
    key: 'therapist',
    title: 'Therapist',
  },
  {
    key: 'manager',
    title: 'Manager',
  },
  {
    key: 'director',
    title: 'Director',
  },
  {
    key: 'admin',
    title: 'Admin',
  },
]

export const data = [
  {
    key: '1',
    name: 'Contact Reports',
    children: [
      {
        key: 'CO001',
        name: 'CO001 - Basic Information',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO003',
        name: 'CO003 - Birthday',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO010',
        name: 'CO010 - Outstanding Packages',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO020',
        name: 'CO020 - New Clients',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO030',
        name: 'CO030 - Last Spend',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO031',
        name: 'CO031 - Last Visit',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO035',
        name: 'CO035 - Clients by Location',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO046',
        name: 'CO046 - First Visit',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'VA001',
        name: 'VA001 - Vaccination Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO045',
        name: 'CO045 - Big Spender by Receipt',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO050',
        name: 'CO050 - Client Receipts by Category',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO065',
        name: 'CO065 - Client Retail Purchases',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO070',
        name: 'CO070 - Account Balance',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO075',
        name: 'CO075 - Client Service Sales',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO147',
        name: 'CO147 - Medical Data Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO060',
        name: 'CO060 - Duplicate Clients',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO105',
        name: 'CO105 - Patient Prescriptions',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO110',
        name: 'CO110 - Clients Treatment Interest',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO111',
        name: 'CO111 - Never Purchased Before',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO115',
        name: 'CO115 - Client Enquiry Conversion',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO130',
        name: 'CO130 - Product Consumption',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO135',
        name: 'CO135 - Account Activity',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO140',
        name: 'CO140 - Last Customer Bookings by Employee',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO145',
        name: 'CO145 - Account Balance by Date',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO146',
        name: 'CO146 - Treatment Missing Data',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
  {
    key: '2',
    name: 'Marketing Reports',
    children: [
      {
        key: 'CO095',
        name: 'CO095 - Client Recalls',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO100',
        name: 'CO100 - Loyalty Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO085',
        name: 'CO085 - Gift Cards',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO090',
        name: 'CO090 - Gift Card Analysis',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'MA001',
        name: 'MA001 - Sales by Referral Source',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'MA005',
        name: 'MA005 - Opt In Text Contacts',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'MA010',
        name: 'MA010 - Opt In Email Contacts',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'MA020',
        name: 'MA020 - Referral Sources',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'MA025',
        name: 'MA025 - Feedback Results',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'MA030',
        name: 'MA030 - Survey Feedback',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
  {
    key: '3',
    name: 'Finance Reports',
    children: [
      {
        key: 'FI000',
        name: 'FI000 - Daily Sales',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI001',
        name: 'FI001 - Daily Reconciliation',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI002',
        name: 'FI002 - Daily Payments',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI005',
        name: 'FI005 - Receipts by Employee - Detailed',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI006',
        name: 'FI006 - Sales by Employee Detailed Cross',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI010',
        name: 'FI010 - Receipts by Retail Category',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI011',
        name: 'FI011 - Receipts by Service Category',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI012',
        name: 'FI012 - Receipts by Category',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI014',
        name: 'FI014 - Sales by Category',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI015',
        name: 'FI015 - Receipts by Employee (Service)',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI016',
        name: 'FI016 - Receipts by Employee (Retail)',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI019',
        name: 'FI019 - VAT Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI025',
        name: 'FI025 - Receipts by Month',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI026',
        name: 'FI026 - Monthly Taking (Summary)',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI030',
        name: 'FI030 - Raised Invoices',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI040',
        name: 'FI040 - Expenses',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI075',
        name: 'FI075 - Outstanding Invoices',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI085',
        name: 'FI085 - Service vs Retail Receipts',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI090',
        name: 'FI090 - Aged Insurance Debt Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI017',
        name: 'FI017 - Receipts by Employee Detailed (VAT)',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI022',
        name: 'FI022 - Daily Performance Stats',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI031',
        name: 'FI031 - Invoice Activity',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI035',
        name: 'FI035 - Receipts by Payment Method',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI055',
        name: 'FI055 - Unpaid Visits',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI060',
        name: 'FI060 - Free Giveaways',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI065',
        name: 'FI065 - Appointment Income Projection',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI070',
        name: 'FI070 - Discount Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI080',
        name: 'FI080 - Sales vs Expense',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'FI155',
        name: 'FI155 - Insurance Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'OT001',
        name: 'OT001 - Sales Conversion',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'OT002',
        name: 'OT002 - Telesales Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
  {
    key: '4',
    name: 'Lead Reports',
    children: [
      {
        key: 'LE000',
        name: 'LE000 - Open Leads',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'LE001',
        name: 'LE001 - Converted Leads',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'LE005',
        name: 'LE005 - Leads',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'LE015',
        name: 'LE015 - Leads by Status',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'LE020',
        name: 'LE020 - Leads by Sources',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'LE035',
        name: 'LE035 - Leads by Interest',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'LE040',
        name: 'LE040 - Leads by Clinic',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
  {
    key: '5',
    name: 'Appointments',
    children: [
      {
        key: 'CO021',
        name: 'CO021 - Booked Appointments',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO025',
        name: 'CO025 - Missed/Cancelled Appointments',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO036',
        name: 'CO036 - Connect Registration & Bookings',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO040',
        name: 'CO040 - Consultation Conversion',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO006',
        name: 'CO006 - Appointments by Service Type Count',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO125',
        name: 'CO125 - Surgery Preparations',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'CO140',
        name: 'CO140 - Last Customer Bookings by Employee',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST000',
        name: 'ST000 - Staff Appointment Schedule',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST025',
        name: 'ST025 - Employee Appointment Summary',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'BETA',
        name: 'BETA - Locations Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'OT003',
        name: 'OT003 - Classes and Appointments report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'OT014',
        name: 'OT014 - Room Utilization',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'OT009',
        name: 'OT009 - Clinic Conversion',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
  {
    key: '6',
    name: 'Stock Reports',
    children: [
      {
        key: 'STK001',
        name: 'STK001 - Stock Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'STK005',
        name: 'STK005 - Low Stock',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'STK015',
        name: 'STK015 - Cost of Goods',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'STK025',
        name: 'STK025 - Stock Count',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
  {
    key: '7',
    name: 'Staff Reports',
    children: [
      {
        key: 'Team',
        name: 'Team Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'BETA',
        name: 'BETA - Staff Bookouts',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST001',
        name: 'ST001 - Staff Performance Summary',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST002',
        name: 'ST002 - Commission Summary',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST003',
        name: 'ST003 - Commission Report (Retail)',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST004',
        name: 'ST004 - Staff Performance Tracker',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST005',
        name: 'ST005 - Employee Holidays To Date',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST015',
        name: 'ST015 - Staff Hours',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST025',
        name: 'ST025 - Employee Appointment Summary',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST031',
        name: 'ST031 - Daily Employee Stats (Summary)',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST033',
        name: 'ST033 - Daily Employee Stats',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST035',
        name: 'ST035 - Staff Days Off',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST036',
        name: 'ST036 - Staff Payroll Report',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
      {
        key: 'ST037',
        name: 'ST037 - Staff Clock In/Out',
        permissions: {
          scheduler: true,
          therapist: false,
          manager: false,
          director: true,
          admin: true,
        },
      },
    ],
  },
]
