export const Products = [
  {
    key: 1,
    status: 'Empty',
    name: 'Obagi Skin Toner',
    category: 'Obagi',
    cost: 80,
    retail: 100,
    quantity: 10,
    is_active: true,
  },
  {
    key: 2,
    status: 'Low',
    name: 'Srx Cream',
    category: 'Obagi',
    cost: 40,
    retail: 75,
    quantity: 4,
    is_active: true,
  },
  {
    key: 3,
    status: 'Good',
    name: 'Eye Serum',
    category: 'Creams',
    cost: 80,
    retail: 100,
    quantity: 15,
    is_active: true,
  },
]

export const Category = [
  {
    key: 1,
    status: true,
    name: 'Skin Creams',
    groupName: 'Skin Creams',
    productsAssigned: 2,
    is_active: true,
  },
  {
    key: 2,
    status: true,
    name: 'Products',
    groupName: 'Products',
    productsAssigned: 4,
    is_active: true,
  },
  {
    key: 3,
    status: true,
    name: 'Injectables',
    groupName: 'Injectables',
    productsAssigned: 6,
    is_active: true,
  },
]

export const Supplier = [
  {
    key: 1,
    status: true,
    name: 'Skin Creams',
    productsAssigned: 2,
    is_active: true,
  },
  {
    key: 2,
    status: true,
    name: 'Products',
    productsAssigned: 9,
    is_active: true,
  },
  {
    key: 3,
    status: true,
    name: 'Injectables',
    productsAssigned: 0,
    is_active: true,
  },
]
export const PurchaseOrder = [
  {
    key: 1,
    PONumber: 'PO1828',
    createdDate: '06/11/2022',
    supplier: 'Skin Creams',
    createdBy: 'William Brandham',
    location: 'London',
    totalCost: 100,
    status: true,
    is_active: true,
  },
  {
    key: 2,
    PONumber: 'PO82828',
    createdDate: '11/11/2022',
    supplier: 'Jim Smith',
    createdBy: 'James Bond',
    location: 'Leeds',
    totalCost: 500,
    status: true,
    is_active: true,
  },
  {
    key: 3,
    PONumber: 'PO2828',
    createdDate: '18/12/2020',
    supplier: 'Injectables',
    createdBy: 'Jim Smith',
    location: 'Liverpool',
    totalCost: 900,
    status: true,
    is_active: true,
  },
]
export const StokeTake = [
  {
    key: 1,
    countNO: 'PO1828',
    name: 'Skin Creams',
    startDate: '06/11/2022',
    countedBy: 'William Brandham',
    location: 'London',
    total: 32,
    discrepancies: {
      up: 8,
      down: 3,
    },
    status: 'Completed',
  },
  {
    key: 2,
    countNO: 'PO1828',
    name: 'Skin Creams',
    startDate: '11/11/2022',
    countedBy: 'James Bond',
    location: 'Paris',
    total: 4,
    discrepancies: {
      up: 8,
      down: 3,
    },
    status: 'Started',
  },
  {
    key: 3,
    countNO: 'PO1828',
    name: 'Skin Creams',
    startDate: '18/12/2020',
    countedBy: 'James Bond',
    location: 'New York',
    total: 7,
    discrepancies: {
      up: 8,
      down: 3,
    },
    status: 'Cancelled',
  },
]
