const currency = [
  'United States dollar',
  'Euro',
  'Japanese yen',
  'Pound sterling',
  'Australian dollar',
  'Canadian dollar',
  'Swiss franc',
  'Renminbi',
  'Hong Kong dollar',
  'New Zealand dollar',
  'Swedish krona',
  'South Korean won',
  'Singapore dollar',
  'Norwegian krone',
  'Mexican peso',
  'Indian rupee',
  'Russian ruble',
  'South African rand',
  'Turkish lira',
  'Brazilian real',
  'New Taiwan dollar',
  'Danish krone',
  'Polish złoty',
  'Thai baht',
  'Indonesian rupiah',
  'Hungarian forint',
  'Czech koruna',
  'Israeli new shekel',
  'Chilean peso',
  'Philippine peso',
  'UAE dirham',
  'Colombian peso',
  'Saudi riyal',
  'Malaysian ringgit',
  'Romanian leu',
]

export default currency
