const timezone = [
  { timezone: 'Pacific/Pago_Pago', text: '(GMT -11:00) Pago Pago' },
  { timezone: 'Pacific/Niue', text: '(GMT -11:00) Niue' },
  { timezone: 'Pacific/Midway', text: '(GMT -11:00) Midway' },
  { timezone: 'Pacific/Rarotonga', text: '(GMT -10:00) Rarotonga' },
  { timezone: 'Pacific/Tahiti', text: '(GMT -10:00) Tahiti' },
  { timezone: 'America/Adak', text: '(GMT -10:00) Adak' },
  { timezone: 'Pacific/Honolulu', text: '(GMT -10:00) Honolulu' },
  { timezone: 'Pacific/Marquesas', text: '(GMT -09:30) Marquesas' },
  { timezone: 'Pacific/Gambier', text: '(GMT -09:00) Gambier' },
  { timezone: 'America/Anchorage', text: '(GMT -09:00) Anchorage' },
  { timezone: 'America/Juneau', text: '(GMT -09:00) Juneau' },
  { timezone: 'America/Sitka', text: '(GMT -09:00) Sitka' },
  { timezone: 'America/Metlakatla', text: '(GMT -09:00) Metlakatla' },
  { timezone: 'America/Yakutat', text: '(GMT -09:00) Yakutat' },
  { timezone: 'America/Nome', text: '(GMT -09:00) Nome' },
  { timezone: 'America/Vancouver', text: '(GMT -08:00) Vancouver' },
  { timezone: 'America/Whitehorse', text: '(GMT -08:00) Whitehorse' },
  { timezone: 'America/Dawson', text: '(GMT -08:00) Dawson' },
  { timezone: 'America/Tijuana', text: '(GMT -08:00) Tijuana' },
  { timezone: 'Pacific/Pitcairn', text: '(GMT -08:00) Pitcairn' },
  { timezone: 'America/Los_Angeles', text: '(GMT -08:00) Los Angeles' },
  { timezone: 'America/Edmonton', text: '(GMT -07:00) Edmonton' },
  { timezone: 'America/Cambridge_Bay', text: '(GMT -07:00) Cambridge Bay' },
  { timezone: 'America/Yellowknife', text: '(GMT -07:00) Yellowknife' },
  { timezone: 'America/Inuvik', text: '(GMT -07:00) Inuvik' },
  { timezone: 'America/Creston', text: '(GMT -07:00) Creston' },
  { timezone: 'America/Dawson_Creek', text: '(GMT -07:00) Dawson Creek' },
  { timezone: 'America/Fort_Nelson', text: '(GMT -07:00) Fort Nelson' },
  { timezone: 'America/Mazatlan', text: '(GMT -07:00) Mazatlan' },
  { timezone: 'America/Chihuahua', text: '(GMT -07:00) Chihuahua' },
  { timezone: 'America/Ojinaga', text: '(GMT -07:00) Ojinaga' },
  { timezone: 'America/Hermosillo', text: '(GMT -07:00) Hermosillo' },
  { timezone: 'America/Bahia_Banderas', text: '(GMT -07:00) Bahia Banderas' },
  { timezone: 'America/Denver', text: '(GMT -07:00) Denver' },
  { timezone: 'America/Boise', text: '(GMT -07:00) Boise' },
  { timezone: 'America/Phoenix', text: '(GMT -07:00) Phoenix' },
  { timezone: 'America/Belize', text: '(GMT -06:00) Belize' },
  { timezone: 'America/Winnipeg', text: '(GMT -06:00) Winnipeg' },
  { timezone: 'America/Rainy_River', text: '(GMT -06:00) Rainy River' },
  { timezone: 'America/Resolute', text: '(GMT -06:00) Resolute' },
  { timezone: 'America/Rankin_Inlet', text: '(GMT -06:00) Rankin Inlet' },
  { timezone: 'America/Regina', text: '(GMT -06:00) Regina' },
  { timezone: 'America/Swift_Current', text: '(GMT -06:00) Swift Current' },
  { timezone: 'Pacific/Easter', text: '(GMT -06:00) Easter' },
  { timezone: 'America/Costa_Rica', text: '(GMT -06:00) Costa Rica' },
  { timezone: 'Pacific/Galapagos', text: '(GMT -06:00) Galapagos' },
  { timezone: 'America/Guatemala', text: '(GMT -06:00) Guatemala' },
  { timezone: 'America/Tegucigalpa', text: '(GMT -06:00) Tegucigalpa' },
  { timezone: 'America/Mexico_City', text: '(GMT -06:00) Mexico City' },
  { timezone: 'America/Merida', text: '(GMT -06:00) Merida' },
  { timezone: 'America/Monterrey', text: '(GMT -06:00) Monterrey' },
  { timezone: 'America/Matamoros', text: '(GMT -06:00) Matamoros' },
  { timezone: 'America/Managua', text: '(GMT -06:00) Managua' },
  { timezone: 'America/El_Salvador', text: '(GMT -06:00) El Salvador' },
  { timezone: 'America/Chicago', text: '(GMT -06:00) Chicago' },
  {
    timezone: 'America/Indiana/Tell_City',
    text: '(GMT -06:00) Tell City, Indiana',
  },
  { timezone: 'America/Indiana/Knox', text: '(GMT -06:00) Knox, Indiana' },
  { timezone: 'America/Menominee', text: '(GMT -06:00) Menominee' },
  {
    timezone: 'America/North_Dakota/Center',
    text: '(GMT -06:00) Center, North Dakota',
  },
  {
    timezone: 'America/North_Dakota/New_Salem',
    text: '(GMT -06:00) New Salem, North Dakota',
  },
  {
    timezone: 'America/North_Dakota/Beulah',
    text: '(GMT -06:00) Beulah, North Dakota',
  },
  { timezone: 'America/Eirunepe', text: '(GMT -05:00) Eirunepe' },
  { timezone: 'America/Rio_Branco', text: '(GMT -05:00) Rio Branco' },
  { timezone: 'America/Nassau', text: '(GMT -05:00) Nassau' },
  { timezone: 'America/Toronto', text: '(GMT -05:00) Toronto' },
  { timezone: 'America/Nipigon', text: '(GMT -05:00) Nipigon' },
  { timezone: 'America/Thunder_Bay', text: '(GMT -05:00) Thunder Bay' },
  { timezone: 'America/Iqaluit', text: '(GMT -05:00) Iqaluit' },
  { timezone: 'America/Pangnirtung', text: '(GMT -05:00) Pangnirtung' },
  { timezone: 'America/Atikokan', text: '(GMT -05:00) Atikokan' },
  { timezone: 'America/Bogota', text: '(GMT -05:00) Bogota' },
  { timezone: 'America/Havana', text: '(GMT -05:00) Havana' },
  { timezone: 'America/Guayaquil', text: '(GMT -05:00) Guayaquil' },
  { timezone: 'America/Port-a,text:  -Prince' > '(GMT -05:00) Port-au-Prince' },
  { timezone: 'America/Jamaica', text: '(GMT -05:00) Jamaica' },
  { timezone: 'America/Cayman', text: '(GMT -05:00) Cayman' },
  { timezone: 'America/Cancun', text: '(GMT -05:00) Cancun' },
  { timezone: 'America/Panama', text: '(GMT -05:00) Panama' },
  { timezone: 'America/Lima', text: '(GMT -05:00) Lima' },
  { timezone: 'America/Grand_Turk', text: '(GMT -05:00) Grand Turk' },
  { timezone: 'America/New_York', text: '(GMT -05:00) New York' },
  { timezone: 'America/Detroit', text: '(GMT -05:00) Detroit' },
  {
    timezone: 'America/Kentucky/Louisville',
    text: '(GMT -05:00) Louisville, Kentucky',
  },
  {
    timezone: 'America/Kentucky/Monticello',
    text: '(GMT -05:00) Monticello, Kentucky',
  },
  {
    timezone: 'America/Indiana/Indianapolis',
    text: '(GMT -05:00) Indianapolis, Indiana',
  },
  {
    timezone: 'America/Indiana/Vincennes',
    text: '(GMT -05:00) Vincennes, Indiana',
  },
  {
    timezone: 'America/Indiana/Winamac',
    text: '(GMT -05:00) Winamac, Indiana',
  },
  {
    timezone: 'America/Indiana/Marengo',
    text: '(GMT -05:00) Marengo, Indiana',
  },
  {
    timezone: 'America/Indiana/Petersburg',
    text: '(GMT -05:00) Petersburg, Indiana',
  },
  { timezone: 'America/Indiana/Vevay', text: '(GMT -05:00) Vevay, Indiana' },
  { timezone: 'America/Antigua', text: '(GMT -04:00) Antigua' },
  { timezone: 'America/Anguilla', text: '(GMT -04:00) Anguilla' },
  { timezone: 'America/Aruba', text: '(GMT -04:00) Aruba' },
  { timezone: 'America/Barbados', text: '(GMT -04:00) Barbados' },
  { timezone: 'America/St_Barthelemy', text: '(GMT -04:00) St Barthelemy' },
  { timezone: 'Atlantic/Bermuda', text: '(GMT -04:00) Bermuda' },
  { timezone: 'America/La_Paz', text: '(GMT -04:00) La Paz' },
  { timezone: 'America/Kralendijk', text: '(GMT -04:00) Kralendijk' },
  { timezone: 'America/Campo_Grande', text: '(GMT -04:00) Campo Grande' },
  { timezone: 'America/Cuiaba', text: '(GMT -04:00) Cuiaba' },
  { timezone: 'America/Porto_Velho', text: '(GMT -04:00) Porto Velho' },
  { timezone: 'America/Boa_Vista', text: '(GMT -04:00) Boa Vista' },
  { timezone: 'America/Manaus', text: '(GMT -04:00) Manaus' },
  { timezone: 'America/Halifax', text: '(GMT -04:00) Halifax' },
  { timezone: 'America/Glace_Bay', text: '(GMT -04:00) Glace Bay' },
  { timezone: 'America/Moncton', text: '(GMT -04:00) Moncton' },
  { timezone: 'America/Goose_Bay', text: '(GMT -04:00) Goose Bay' },
  { timezone: 'America/Blanc-S,text:  blon' > '(GMT -04:00) Blanc-Sablon' },
  { timezone: 'America/Santiago', text: '(GMT -04:00) Santiago' },
  { timezone: 'America/Curacao', text: '(GMT -04:00) Curacao' },
  { timezone: 'America/Dominica', text: '(GMT -04:00) Dominica' },
  { timezone: 'America/Santo_Domingo', text: '(GMT -04:00) Santo Domingo' },
  { timezone: 'America/Grenada', text: '(GMT -04:00) Grenada' },
  { timezone: 'America/Thule', text: '(GMT -04:00) Thule' },
  { timezone: 'America/Guadeloupe', text: '(GMT -04:00) Guadeloupe' },
  { timezone: 'America/Guyana', text: '(GMT -04:00) Guyana' },
  { timezone: 'America/St_Kitts', text: '(GMT -04:00) St Kitts' },
  { timezone: 'America/St_Lucia', text: '(GMT -04:00) St Lucia' },
  { timezone: 'America/Marigot', text: '(GMT -04:00) Marigot' },
  { timezone: 'America/Martinique', text: '(GMT -04:00) Martinique' },
  { timezone: 'America/Montserrat', text: '(GMT -04:00) Montserrat' },
  { timezone: 'America/Puerto_Rico', text: '(GMT -04:00) Puerto Rico' },
  { timezone: 'America/Asuncion', text: '(GMT -04:00) Asuncion' },
  { timezone: 'America/Lower_Princes', text: '(GMT -04:00) Lower Princes' },
  { timezone: 'America/Port_of_Spain', text: '(GMT -04:00) Port of Spain' },
  { timezone: 'America/St_Vincent', text: '(GMT -04:00) St Vincent' },
  { timezone: 'America/Caracas', text: '(GMT -04:00) Caracas' },
  { timezone: 'America/Tortola', text: '(GMT -04:00) Tortola' },
  { timezone: 'America/St_Thomas', text: '(GMT -04:00) St Thomas' },
  { timezone: 'America/St_Johns', text: '(GMT -03:30) St Johns' },
  { timezone: 'Antarctica/Palmer', text: '(GMT -03:00) Palmer' },
  { timezone: 'Antarctica/Rothera', text: '(GMT -03:00) Rothera' },
  {
    timezone: 'America/Argentina/Buenos_Aires',
    text: '(GMT -03:00) Buenos Aires, Argentina',
  },
  {
    timezone: 'America/Argentina/Cordoba',
    text: '(GMT -03:00) Cordoba, Argentina',
  },
  {
    timezone: 'America/Argentina/Salta',
    text: '(GMT -03:00) Salta, Argentina',
  },
  {
    timezone: 'America/Argentina/Jujuy',
    text: '(GMT -03:00) Jujuy, Argentina',
  },
  {
    timezone: 'America/Argentina/Tucuman',
    text: '(GMT -03:00) Tucuman, Argentina',
  },
  {
    timezone: 'America/Argentina/Catamarca',
    text: '(GMT -03:00) Catamarca, Argentina',
  },
  {
    timezone: 'America/Argentina/La_Rioja',
    text: '(GMT -03:00) La Rioja, Argentina',
  },
  {
    timezone: 'America/Argentina/San_Juan',
    text: '(GMT -03:00) San Juan, Argentina',
  },
  {
    timezone: 'America/Argentina/Mendoza',
    text: '(GMT -03:00) Mendoza, Argentina',
  },
  {
    timezone: 'America/Argentina/San_Luis',
    text: '(GMT -03:00) San Luis, Argentina',
  },
  {
    timezone: 'America/Argentina/Rio_Gallegos',
    text: '(GMT -03:00) Rio Gallegos, Argentina',
  },
  {
    timezone: 'America/Argentina/Ushuaia',
    text: '(GMT -03:00) Ushuaia, Argentina',
  },
  { timezone: 'America/Belem', text: '(GMT -03:00) Belem' },
  { timezone: 'America/Fortaleza', text: '(GMT -03:00) Fortaleza' },
  { timezone: 'America/Recife', text: '(GMT -03:00) Recife' },
  { timezone: 'America/Araguaina', text: '(GMT -03:00) Araguaina' },
  { timezone: 'America/Maceio', text: '(GMT -03:00) Maceio' },
  { timezone: 'America/Bahia', text: '(GMT -03:00) Bahia' },
  { timezone: 'America/Sao_Paulo', text: '(GMT -03:00) Sao Paulo' },
  { timezone: 'America/Santarem', text: '(GMT -03:00) Santarem' },
  { timezone: 'America/Punta_Arenas', text: '(GMT -03:00) Punta Arenas' },
  { timezone: 'Atlantic/Stanley', text: '(GMT -03:00) Stanley' },
  { timezone: 'America/Cayenne', text: '(GMT -03:00) Cayenne' },
  { timezone: 'America/Godthab', text: '(GMT -03:00) Godthab' },
  { timezone: 'America/Miquelon', text: '(GMT -03:00) Miquelon' },
  { timezone: 'America/Paramaribo', text: '(GMT -03:00) Paramaribo' },
  { timezone: 'America/Montevideo', text: '(GMT -03:00) Montevideo' },
  { timezone: 'America/Noronha', text: '(GMT -02:00) Noronha' },
  { timezone: 'Atlantic/South_Georgia', text: '(GMT -02:00) South Georgia' },
  { timezone: 'Atlantic/Cape_Verde', text: '(GMT -01:00) Cape Verde' },
  { timezone: 'America/Scoresbysund', text: '(GMT -01:00) Scoresbysund' },
  { timezone: 'Atlantic/Azores', text: '(GMT -01:00) Azores' },
  { timezone: 'Antarctica/Troll', text: '(GMT +00:00) Troll' },
  { timezone: 'Africa/Ouagadougou', text: '(GMT +00:00) Ouagadougou' },
  { timezone: 'Africa/Abidjan', text: '(GMT +00:00) Abidjan' },
  { timezone: 'Africa/El_Aaiun', text: '(GMT +00:00) El Aaiun' },
  { timezone: 'Atlantic/Canary', text: '(GMT +00:00) Canary' },
  { timezone: 'Atlantic/Faroe', text: '(GMT +00:00) Faroe' },
  { timezone: 'Europe/London', text: '(GMT +00:00) London' },
  { timezone: 'Europe/Guernsey', text: '(GMT +00:00) Guernsey' },
  { timezone: 'Africa/Accra', text: '(GMT +00:00) Accra' },
  { timezone: 'America/Danmarkshavn', text: '(GMT +00:00) Danmarkshavn' },
  { timezone: 'Africa/Banjul', text: '(GMT +00:00) Banjul' },
  { timezone: 'Africa/Conakry', text: '(GMT +00:00) Conakry' },
  { timezone: 'Africa/Bissau', text: '(GMT +00:00) Bissau' },
  { timezone: 'Europe/Dublin', text: '(GMT +00:00) Dublin' },
  { timezone: 'Europe/Isle_of_Man', text: '(GMT +00:00) Isle of Man' },
  { timezone: 'Atlantic/Reykjavik', text: '(GMT +00:00) Reykjavik' },
  { timezone: 'Europe/Jersey', text: '(GMT +00:00) Jersey' },
  { timezone: 'Africa/Monrovia', text: '(GMT +00:00) Monrovia' },
  { timezone: 'Africa/Casablanca', text: '(GMT +00:00) Casablanca' },
  { timezone: 'Africa/Bamako', text: '(GMT +00:00) Bamako' },
  { timezone: 'Africa/Nouakchott', text: '(GMT +00:00) Nouakchott' },
  { timezone: 'Europe/Lisbon', text: '(GMT +00:00) Lisbon' },
  { timezone: 'Atlantic/Madeira', text: '(GMT +00:00) Madeira' },
  { timezone: 'Atlantic/St_Helena', text: '(GMT +00:00) St Helena' },
  { timezone: 'Africa/Freetown', text: '(GMT +00:00) Freetown' },
  { timezone: 'Africa/Dakar', text: '(GMT +00:00) Dakar' },
  { timezone: 'Africa/Sao_Tome', text: '(GMT +00:00) Sao Tome' },
  { timezone: 'Africa/Lome', text: '(GMT +00:00) Lome' },
  { timezone: 'Europe/Andorra', text: '(GMT +01:00) Andorra' },
  { timezone: 'Europe/Tirane', text: '(GMT +01:00) Tirane' },
  { timezone: 'Africa/Luanda', text: '(GMT +01:00) Luanda' },
  { timezone: 'Europe/Vienna', text: '(GMT +01:00) Vienna' },
  { timezone: 'Europe/Sarajevo', text: '(GMT +01:00) Sarajevo' },
  { timezone: 'Europe/Brussels', text: '(GMT +01:00) Brussels' },
  { timezone: 'Africa/Porto-N,text:  vo' > '(GMT +01:00) Porto-Novo' },
  { timezone: 'Africa/Kinshasa', text: '(GMT +01:00) Kinshasa' },
  { timezone: 'Africa/Bangui', text: '(GMT +01:00) Bangui' },
  { timezone: 'Africa/Brazzaville', text: '(GMT +01:00) Brazzaville' },
  { timezone: 'Europe/Zurich', text: '(GMT +01:00) Zurich' },
  { timezone: 'Africa/Douala', text: '(GMT +01:00) Douala' },
  { timezone: 'Europe/Prague', text: '(GMT +01:00) Prague' },
  { timezone: 'Europe/Berlin', text: '(GMT +01:00) Berlin' },
  { timezone: 'Europe/Busingen', text: '(GMT +01:00) Busingen' },
  { timezone: 'Europe/Copenhagen', text: '(GMT +01:00) Copenhagen' },
  { timezone: 'Africa/Algiers', text: '(GMT +01:00) Algiers' },
  { timezone: 'Europe/Madrid', text: '(GMT +01:00) Madrid' },
  { timezone: 'Africa/Ceuta', text: '(GMT +01:00) Ceuta' },
  { timezone: 'Europe/Paris', text: '(GMT +01:00) Paris' },
  { timezone: 'Africa/Libreville', text: '(GMT +01:00) Libreville' },
  { timezone: 'Europe/Gibraltar', text: '(GMT +01:00) Gibraltar' },
  { timezone: 'Africa/Malabo', text: '(GMT +01:00) Malabo' },
  { timezone: 'Europe/Zagreb', text: '(GMT +01:00) Zagreb' },
  { timezone: 'Europe/Budapest', text: '(GMT +01:00) Budapest' },
  { timezone: 'Europe/Rome', text: '(GMT +01:00) Rome' },
  { timezone: 'Europe/Vaduz', text: '(GMT +01:00) Vaduz' },
  { timezone: 'Europe/Luxembourg', text: '(GMT +01:00) Luxembourg' },
  { timezone: 'Europe/Monaco', text: '(GMT +01:00) Monaco' },
  { timezone: 'Europe/Podgorica', text: '(GMT +01:00) Podgorica' },
  { timezone: 'Europe/Skopje', text: '(GMT +01:00) Skopje' },
  { timezone: 'Europe/Malta', text: '(GMT +01:00) Malta' },
  { timezone: 'Africa/Niamey', text: '(GMT +01:00) Niamey' },
  { timezone: 'Africa/Lagos', text: '(GMT +01:00) Lagos' },
  { timezone: 'Europe/Amsterdam', text: '(GMT +01:00) Amsterdam' },
  { timezone: 'Europe/Oslo', text: '(GMT +01:00) Oslo' },
  { timezone: 'Europe/Warsaw', text: '(GMT +01:00) Warsaw' },
  { timezone: 'Europe/Belgrade', text: '(GMT +01:00) Belgrade' },
  { timezone: 'Europe/Stockholm', text: '(GMT +01:00) Stockholm' },
  { timezone: 'Europe/Ljubljana', text: '(GMT +01:00) Ljubljana' },
  { timezone: 'Arctic/Longyearbyen', text: '(GMT +01:00) Longyearbyen' },
  { timezone: 'Europe/Bratislava', text: '(GMT +01:00) Bratislava' },
  { timezone: 'Europe/San_Marino', text: '(GMT +01:00) San Marino' },
  { timezone: 'Africa/Ndjamena', text: '(GMT +01:00) Ndjamena' },
  { timezone: 'Africa/Tunis', text: '(GMT +01:00) Tunis' },
  { timezone: 'Europe/Vatican', text: '(GMT +01:00) Vatican' },
  { timezone: 'Europe/Mariehamn', text: '(GMT +02:00) Mariehamn' },
  { timezone: 'Europe/Sofia', text: '(GMT +02:00) Sofia' },
  { timezone: 'Africa/Bujumbura', text: '(GMT +02:00) Bujumbura' },
  { timezone: 'Africa/Gaborone', text: '(GMT +02:00) Gaborone' },
  { timezone: 'Africa/Lubumbashi', text: '(GMT +02:00) Lubumbashi' },
  { timezone: 'Asia/Nicosia', text: '(GMT +02:00) Nicosia' },
  { timezone: 'Asia/Famagusta', text: '(GMT +02:00) Famagusta' },
  { timezone: 'Europe/Tallinn', text: '(GMT +02:00) Tallinn' },
  { timezone: 'Africa/Cairo', text: '(GMT +02:00) Cairo' },
  { timezone: 'Europe/Helsinki', text: '(GMT +02:00) Helsinki' },
  { timezone: 'Europe/Athens', text: '(GMT +02:00) Athens' },
  { timezone: 'Asia/Jerusalem', text: '(GMT +02:00) Jerusalem' },
  { timezone: 'Asia/Amman', text: '(GMT +02:00) Amman' },
  { timezone: 'Asia/Beirut', text: '(GMT +02:00) Beirut' },
  { timezone: 'Africa/Maseru', text: '(GMT +02:00) Maseru' },
  { timezone: 'Europe/Vilnius', text: '(GMT +02:00) Vilnius' },
  { timezone: 'Europe/Riga', text: '(GMT +02:00) Riga' },
  { timezone: 'Africa/Tripoli', text: '(GMT +02:00) Tripoli' },
  { timezone: 'Europe/Chisinau', text: '(GMT +02:00) Chisinau' },
  { timezone: 'Africa/Blantyre', text: '(GMT +02:00) Blantyre' },
  { timezone: 'Africa/Maputo', text: '(GMT +02:00) Maputo' },
  { timezone: 'Africa/Windhoek', text: '(GMT +02:00) Windhoek' },
  { timezone: 'Asia/Gaza', text: '(GMT +02:00) Gaza' },
  { timezone: 'Asia/Hebron', text: '(GMT +02:00) Hebron' },
  { timezone: 'Europe/Bucharest', text: '(GMT +02:00) Bucharest' },
  { timezone: 'Europe/Kaliningrad', text: '(GMT +02:00) Kaliningrad' },
  { timezone: 'Africa/Kigali', text: '(GMT +02:00) Kigali' },
  { timezone: 'Africa/Khartoum', text: '(GMT +02:00) Khartoum' },
  { timezone: 'Asia/Damascus', text: '(GMT +02:00) Damascus' },
  { timezone: 'Africa/Mbabane', text: '(GMT +02:00) Mbabane' },
  { timezone: 'Europe/Kiev', text: '(GMT +02:00) Kiev' },
  { timezone: 'Europe/Uzhgorod', text: '(GMT +02:00) Uzhgorod' },
  { timezone: 'Europe/Zaporozhye', text: '(GMT +02:00) Zaporozhye' },
  { timezone: 'Africa/Johannesburg', text: '(GMT +02:00) Johannesburg' },
  { timezone: 'Africa/Lusaka', text: '(GMT +02:00) Lusaka' },
  { timezone: 'Africa/Harare', text: '(GMT +02:00) Harare' },
  { timezone: 'Antarctica/Syowa', text: '(GMT +03:00) Syowa' },
  { timezone: 'Asia/Bahrain', text: '(GMT +03:00) Bahrain' },
  { timezone: 'Europe/Minsk', text: '(GMT +03:00) Minsk' },
  { timezone: 'Africa/Djibouti', text: '(GMT +03:00) Djibouti' },
  { timezone: 'Africa/Asmara', text: '(GMT +03:00) Asmara' },
  { timezone: 'Africa/Addis_Ababa', text: '(GMT +03:00) Addis Ababa' },
  { timezone: 'Asia/Baghdad', text: '(GMT +03:00) Baghdad' },
  { timezone: 'Africa/Nairobi', text: '(GMT +03:00) Nairobi' },
  { timezone: 'Indian/Comoro', text: '(GMT +03:00) Comoro' },
  { timezone: 'Asia/Kuwait', text: '(GMT +03:00) Kuwait' },
  { timezone: 'Indian/Antananarivo', text: '(GMT +03:00) Antananarivo' },
  { timezone: 'Asia/Qatar', text: '(GMT +03:00) Qatar' },
  { timezone: 'Europe/Moscow', text: '(GMT +03:00) Moscow' },
  { timezone: 'Europe/Simferopol', text: '(GMT +03:00) Simferopol' },
  { timezone: 'Europe/Volgograd', text: '(GMT +03:00) Volgograd' },
  { timezone: 'Europe/Kirov', text: '(GMT +03:00) Kirov' },
  { timezone: 'Asia/Riyadh', text: '(GMT +03:00) Riyadh' },
  { timezone: 'Africa/Mogadishu', text: '(GMT +03:00) Mogadishu' },
  { timezone: 'Africa/Juba', text: '(GMT +03:00) Juba' },
  { timezone: 'Europe/Istanbul', text: '(GMT +03:00) Istanbul' },
  { timezone: 'Africa/Dar_es_Salaam', text: '(GMT +03:00) Dar es Salaam' },
  { timezone: 'Africa/Kampala', text: '(GMT +03:00) Kampala' },
  { timezone: 'Asia/Aden', text: '(GMT +03:00) Aden' },
  { timezone: 'Indian/Mayotte', text: '(GMT +03:00) Mayotte' },
  { timezone: 'Asia/Tehran', text: '(GMT +03:30) Tehran' },
  { timezone: 'Asia/Dubai', text: '(GMT +04:00) Dubai' },
  { timezone: 'Asia/Yerevan', text: '(GMT +04:00) Yerevan' },
  { timezone: 'Asia/Baku', text: '(GMT +04:00) Baku' },
  { timezone: 'Asia/Tbilisi', text: '(GMT +04:00) Tbilisi' },
  { timezone: 'Indian/Mauritius', text: '(GMT +04:00) Mauritius' },
  { timezone: 'Asia/Muscat', text: '(GMT +04:00) Muscat' },
  { timezone: 'Indian/Reunion', text: '(GMT +04:00) Reunion' },
  { timezone: 'Europe/Astrakhan', text: '(GMT +04:00) Astrakhan' },
  { timezone: 'Europe/Saratov', text: '(GMT +04:00) Saratov' },
  { timezone: 'Europe/Ulyanovsk', text: '(GMT +04:00) Ulyanovsk' },
  { timezone: 'Europe/Samara', text: '(GMT +04:00) Samara' },
  { timezone: 'Indian/Mahe', text: '(GMT +04:00) Mahe' },
  { timezone: 'Asia/Kabul', text: '(GMT +04:30) Kabul' },
  { timezone: 'Antarctica/Mawson', text: '(GMT +05:00) Mawson' },
  { timezone: 'Asia/Aqtobe', text: '(GMT +05:00) Aqtobe' },
  { timezone: 'Asia/Aqtau', text: '(GMT +05:00) Aqtau' },
  { timezone: 'Asia/Atyrau', text: '(GMT +05:00) Atyrau' },
  { timezone: 'Asia/Oral', text: '(GMT +05:00) Oral' },
  { timezone: 'Indian/Maldives', text: '(GMT +05:00) Maldives' },
  { timezone: 'Asia/Karachi', text: '(GMT +05:00) Karachi' },
  { timezone: 'Asia/Yekaterinburg', text: '(GMT +05:00) Yekaterinburg' },
  { timezone: 'Indian/Kerguelen', text: '(GMT +05:00) Kerguelen' },
  { timezone: 'Asia/Dushanbe', text: '(GMT +05:00) Dushanbe' },
  { timezone: 'Asia/Ashgabat', text: '(GMT +05:00) Ashgabat' },
  { timezone: 'Asia/Samarkand', text: '(GMT +05:00) Samarkand' },
  { timezone: 'Asia/Tashkent', text: '(GMT +05:00) Tashkent' },
  { timezone: 'Asia/Kolkata', text: '(GMT +05:30) Kolkata' },
  { timezone: 'Asia/Colombo', text: '(GMT +05:30) Colombo' },
  { timezone: 'Asia/Kathmandu', text: '(GMT +05:45) Kathmandu' },
  { timezone: 'Antarctica/Vostok', text: '(GMT +06:00) Vostok' },
  { timezone: 'Asia/Dhaka', text: '(GMT +06:00) Dhaka' },
  { timezone: 'Asia/Thimphu', text: '(GMT +06:00) Thimphu' },
  { timezone: 'Asia/Urumqi', text: '(GMT +06:00) Urumqi' },
  { timezone: 'Indian/Chagos', text: '(GMT +06:00) Chagos' },
  { timezone: 'Asia/Bishkek', text: '(GMT +06:00) Bishkek' },
  { timezone: 'Asia/Almaty', text: '(GMT +06:00) Almaty' },
  { timezone: 'Asia/Qyzylorda', text: '(GMT +06:00) Qyzylorda' },
  { timezone: 'Asia/Omsk', text: '(GMT +06:00) Omsk' },
  { timezone: 'Indian/Cocos', text: '(GMT +06:30) Cocos' },
  { timezone: 'Asia/Yangon', text: '(GMT +06:30) Yangon' },
  { timezone: 'Antarctica/Davis', text: '(GMT +07:00) Davis' },
  { timezone: 'Indian/Christmas', text: '(GMT +07:00) Christmas' },
  { timezone: 'Asia/Jakarta', text: '(GMT +07:00) Jakarta' },
  { timezone: 'Asia/Pontianak', text: '(GMT +07:00) Pontianak' },
  { timezone: 'Asia/Phnom_Penh', text: '(GMT +07:00) Phnom Penh' },
  { timezone: 'Asia/Vientiane', text: '(GMT +07:00) Vientiane' },
  { timezone: 'Asia/Hovd', text: '(GMT +07:00) Hovd' },
  { timezone: 'Asia/Novosibirsk', text: '(GMT +07:00) Novosibirsk' },
  { timezone: 'Asia/Barnaul', text: '(GMT +07:00) Barnaul' },
  { timezone: 'Asia/Tomsk', text: '(GMT +07:00) Tomsk' },
  { timezone: 'Asia/Novokuznetsk', text: '(GMT +07:00) Novokuznetsk' },
  { timezone: 'Asia/Krasnoyarsk', text: '(GMT +07:00) Krasnoyarsk' },
  { timezone: 'Asia/Bangkok', text: '(GMT +07:00) Bangkok' },
  { timezone: 'Asia/Ho_Chi_Minh', text: '(GMT +07:00) Ho Chi Minh' },
  { timezone: 'Australia/Perth', text: '(GMT +08:00) Perth' },
  { timezone: 'Asia/Brunei', text: '(GMT +08:00) Brunei' },
  { timezone: 'Asia/Shanghai', text: '(GMT +08:00) Shanghai' },
  { timezone: 'Asia/Hong_Kong', text: '(GMT +08:00) Hong Kong' },
  { timezone: 'Asia/Makassar', text: '(GMT +08:00) Makassar' },
  { timezone: 'Asia/Ulaanbaatar', text: '(GMT +08:00) Ulaanbaatar' },
  { timezone: 'Asia/Choibalsan', text: '(GMT +08:00) Choibalsan' },
  { timezone: 'Asia/Macau', text: '(GMT +08:00) Macau' },
  { timezone: 'Asia/Kuala_Lumpur', text: '(GMT +08:00) Kuala Lumpur' },
  { timezone: 'Asia/Kuching', text: '(GMT +08:00) Kuching' },
  { timezone: 'Asia/Manila', text: '(GMT +08:00) Manila' },
  { timezone: 'Asia/Irkutsk', text: '(GMT +08:00) Irkutsk' },
  { timezone: 'Asia/Singapore', text: '(GMT +08:00) Singapore' },
  { timezone: 'Asia/Taipei', text: '(GMT +08:00) Taipei' },
  { timezone: 'Asia/Pyongyang', text: '(GMT +08:30) Pyongyang' },
  { timezone: 'Australia/Eucla', text: '(GMT +08:45) Eucla' },
  { timezone: 'Asia/Jayapura', text: '(GMT +09:00) Jayapura' },
  { timezone: 'Asia/Tokyo', text: '(GMT +09:00) Tokyo' },
  { timezone: 'Asia/Seoul', text: '(GMT +09:00) Seoul' },
  { timezone: 'Pacific/Palau', text: '(GMT +09:00) Palau' },
  { timezone: 'Asia/Chita', text: '(GMT +09:00) Chita' },
  { timezone: 'Asia/Yakutsk', text: '(GMT +09:00) Yakutsk' },
  { timezone: 'Asia/Khandyga', text: '(GMT +09:00) Khandyga' },
  { timezone: 'Asia/Dili', text: '(GMT +09:00) Dili' },
  { timezone: 'Australia/Broken_Hill', text: '(GMT +09:30) Broken Hill' },
  { timezone: 'Australia/Adelaide', text: '(GMT +09:30) Adelaide' },
  { timezone: 'Australia/Darwin', text: '(GMT +09:30) Darwin' },
  {
    timezone: 'Antarctica/DumontDUrville',
    text: "(GMT +10:00) Dumont D'Urville",
  },
  { timezone: 'Australia/Hobart', text: '(GMT +10:00) Hobart' },
  { timezone: 'Australia/Currie', text: '(GMT +10:00) Currie' },
  { timezone: 'Australia/Melbourne', text: '(GMT +10:00) Melbourne' },
  { timezone: 'Australia/Sydney', text: '(GMT +10:00) Sydney' },
  { timezone: 'Australia/Brisbane', text: '(GMT +10:00) Brisbane' },
  { timezone: 'Australia/Lindeman', text: '(GMT +10:00) Lindeman' },
  { timezone: 'Pacific/Chuuk', text: '(GMT +10:00) Chuuk' },
  { timezone: 'Pacific/Guam', text: '(GMT +10:00) Guam' },
  { timezone: 'Pacific/Saipan', text: '(GMT +10:00) Saipan' },
  { timezone: 'Pacific/Port_Moresby', text: '(GMT +10:00) Port Moresby' },
  { timezone: 'Asia/Vladivostok', text: '(GMT +10:00) Vladivostok' },
  { timezone: 'Asia/Ust-N,text:  ra' > '(GMT +10:00) Ust-Nera' },
  { timezone: 'Australia/Lord_Howe', text: '(GMT +10:30) Lord Howe' },
  { timezone: 'Antarctica/Casey', text: '(GMT +11:00) Casey' },
  { timezone: 'Antarctica/Macquarie', text: '(GMT +11:00) Macquarie' },
  { timezone: 'Pacific/Pohnpei', text: '(GMT +11:00) Pohnpei' },
  { timezone: 'Pacific/Kosrae', text: '(GMT +11:00) Kosrae' },
  { timezone: 'Pacific/Noumea', text: '(GMT +11:00) Noumea' },
  { timezone: 'Pacific/Norfolk', text: '(GMT +11:00) Norfolk' },
  { timezone: 'Pacific/Bougainville', text: '(GMT +11:00) Bougainville' },
  { timezone: 'Asia/Magadan', text: '(GMT +11:00) Magadan' },
  { timezone: 'Asia/Sakhalin', text: '(GMT +11:00) Sakhalin' },
  { timezone: 'Asia/Srednekolymsk', text: '(GMT +11:00) Srednekolymsk' },
  { timezone: 'Pacific/Guadalcanal', text: '(GMT +11:00) Guadalcanal' },
  { timezone: 'Pacific/Efate', text: '(GMT +11:00) Efate' },
  { timezone: 'Antarctica/McMurdo', text: '(GMT +12:00) McMurdo' },
  { timezone: 'Pacific/Fiji', text: '(GMT +12:00) Fiji' },
  { timezone: 'Pacific/Tarawa', text: '(GMT +12:00) Tarawa' },
  { timezone: 'Pacific/Majuro', text: '(GMT +12:00) Majuro' },
  { timezone: 'Pacific/Kwajalein', text: '(GMT +12:00) Kwajalein' },
  { timezone: 'Pacific/Nauru', text: '(GMT +12:00) Nauru' },
  { timezone: 'Pacific/Auckland', text: '(GMT +12:00) Auckland' },
  { timezone: 'Asia/Kamchatka', text: '(GMT +12:00) Kamchatka' },
  { timezone: 'Asia/Anadyr', text: '(GMT +12:00) Anadyr' },
  { timezone: 'Pacific/Funafuti', text: '(GMT +12:00) Funafuti' },
  { timezone: 'Pacific/Wake', text: '(GMT +12:00) Wake' },
  { timezone: 'Pacific/Wallis', text: '(GMT +12:00) Wallis' },
  { timezone: 'Pacific/Chatham', text: '(GMT +12:45) Chatham' },
  { timezone: 'Pacific/Enderbury', text: '(GMT +13:00) Enderbury' },
  { timezone: 'Pacific/Fakaofo', text: '(GMT +13:00) Fakaofo' },
  { timezone: 'Pacific/Tongatapu', text: '(GMT +13:00) Tongatapu' },
  { timezone: 'Pacific/Apia', text: '(GMT +13:00) Apia' },
  { timezone: 'Pacific/Kiritimati', text: '(GMT +14:00) Kiritimati' },
]
export default timezone
